<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $attributeCode = $block->getAttributeCode();
    
    $product = $block->getProduct();
    if (!$attributeCode || !$product) {
        return;
    }
    
    $_attributeValue = $_helper->productAttribute($product, $product->getData($attributeCode), $attributeCode);
    
    if ($_attributeValue): ?>
<div class="product attribute <?php /* @escapeNotVerified */ echo $attributeCode; ?>">
    <div class="value"><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
</div>
<?php endif; ?>
